export const BookIds = [
  "CaPheCungTony",
  "ChinChinChinLaThuGuiChoChinhMinhTapMot",
  "ChuaRuoi",
  "ChuBeCoTaiMoKhoa",
  "DaoMongMo",
  "DiQuaHaiMuaDich",
  "KhiLoiThuocVeNhungViSao",
  "SachNguocDoiXuoi",
  "TatDen",
  "TiengGoiNoiHoangDa",
  "TottoChanBenOCuaSo",
  "VuaMoMatVuaMoCuaSo",
  "VoVanKietNguoiThapLua",
  "KinhChaoTheHeThuTu",
]
